---
- name: Install Docker and Docker Compose
  hosts: '{{ hostname | default("localhost") }}'
  tasks:
    - name: Add Docker Repository
      ansible.builtin.command: yum config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker CE
      ansible.builtin.yum:
        name: docker-ce
        state: latest

    - name: Restart and enable docker
      ansible.builtin.service:
        name: docker
        state: "restarted"
        enabled: true

    - name: Install Docker Compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/v2.29.7/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
