---
- name: Update package list on dc-proxmox-01
  hosts: unzy.home
  become: true  # Utilise sudo pour exécuter les commandes en tant qu'administrateur
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install curl
      apt:
        name: curl
        state: present

    
